networks:
  chain-indexer:

volumes:
  indexer-db-data:

services:
  # traefik reverse proxy with automatic tls management using let encrypt
  traefik:
    image: traefik:v3.6.1
    container_name: traefik
    restart: unless-stopped
    command:
      - --api=false
      - --api.dashboard=false
      - --providers.docker
      - --log.level=info
      - --accesslog=true
      - --accesslog.format=common
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.le.acme.email=alerts@subspace.network
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
    networks:
      - chain-indexer
    environment:
      CF_DNS_API_TOKEN: $CF_DNS_API_TOKEN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json

  indexer-db:
    image: postgres:17-alpine
    container_name: indexer-db
    environment:
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - chain-indexer
    volumes:
      - indexer-db-data:/var/lib/postgresql/data

  chain-indexer:
    image: ghcr.io/autonomys/chain-indexer:${DOCKER_TAG}
    container_name: chain-indexer
    restart: unless-stopped
    networks:
      - chain-indexer
    environment:
      - MIGRATIONS_PATH=/migrations
      - CONSENSUS_RPC=$CONSENSUS_RPC_URL
      - AUTO_EVM_RPC=$AUTO_EVM_RPC_URL
      - DB_URI=postgres://indexer:$DB_PASSWORD@indexer-db:5432/indexer?sslmode=disable
      - PROCESS_BLOCKS_IN_PARALLEL=$PROCESS_BLOCKS_IN_PARALLEL
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.node.loadbalancer.server.port=8080"
      - "traefik.http.routers.node.rule=Host(`indexer.${NETWORK_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.node.tls=true"
      - "traefik.http.routers.node.tls.certresolver=le"
      - "traefik.http.routers.node.entrypoints=websecure"
      - "traefik.http.routers.node.middlewares=redirect-https,rate-limit"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.rate-limit.ratelimit.average=200"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=300"
      - "traefik.http.middlewares.rate-limit.ratelimit.period=1s"
